[build]
  command = "npm install && npm run build"
  publish = "_site" 
  environment = { NODE_VERSION = "18", NODE_ENV = "production" }

# Redirect all paths to index.html for client-side routing (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 